manager:
  cmd: /manager
  image:
    tag: v4.22
    url: quay.io/acm-d/ose-cluster-api-rhel9
webhook:
  image:
    tag: 2.17.0-a412929
    url: quay.io/acm-d/mce-capi-webhook-config-rhel9
imagePullSecret: ""
