manager:
  cmd: /manager
  image:
    tag: v5.0
    url: quay.io/acm-d/ose-cluster-api-rhel9
webhook:
  image:
    tag: 5.0-dev
    url: quay.io/acm-d/mce-capi-webhook-config-rhel9
imagePullSecret: "eyJhdXRocyI6e319"
