# Resource: apps_v1_deployment_capi-system_mce-capi-webhook-config
---
{{- if .Values.global.deployOnOCP }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mce-capi-webhook-config
  name: mce-capi-webhook-config
  namespace: capi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mce-capi-webhook-config
  template:
    metadata:
      labels:
        app: mce-capi-webhook-config
    spec:
      containers:
      - args:
        - --webhook-port=9443
        command:
        - /mce-capi-webhook-config
        image: '{{ .Values.webhook.image.url  }}:{{ .Values.webhook.image.tag  }}'
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccount: mce-labeling-manager
      volumes:
      - name: cert
        secret:
          secretName: mce-capi-webhook-config-service-cert

{{- end }}