# Resource: core_v1_serviceaccount_capi-system_mce-labeling-manager
---
{{- if .Values.global.deployOnOCP }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
  name: mce-labeling-manager
  namespace: capi-system
{{- end }}