# Resource: core_v1_serviceaccount_capi-system_capi-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
  name: capi-manager
  namespace: capi-system