---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mce-label-injector-configmap
  namespace: default
data:
  mce-label-config.yaml: |
    namespace_openshift_cluster_api: "openshift-cluster-api"
    hyper_shift_label_name: "hypershift.openshift.io/hosted-control-plane"
    label_multi_cluster_engine: "multicluster-engine"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mce-label-injector
  labels:
    app: mce-label-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mce-label-injector
  template:
    metadata:
      labels:
        app: mce-label-injector
    spec:
      containers:
      - args:
          - --webhook-port=9443
        image: mce-label-injector
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /etc/webhook/config
          name: webhook-config
          readOnly: true
      volumes:
      - name: cert
        secret:
          secretName: mce-label-injector-certs
      - name: webhook-config
        configMap:
          name: mce-label-injector-configmap
      serviceAccountName: mce-labeling-manager
