---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AROControlPlane
metadata:
 name: ${CS_CLUSTER_NAME}-control-plane
 namespace: ${NAMESPACE}
spec:
 aroClusterName: ${CS_CLUSTER_NAME}
 platform:
   location: ${REGION}
   resourceGroup: ${RESOURCEGROUPNAME}
   subnet: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCEGROUPNAME}/providers/Microsoft.Network/virtualNetworks/${VNET}/subnets/${SUBNET}"
   keyVault: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCEGROUPNAME}/providers/Microsoft.KeyVault/vaults/${KV}"
   outboundType: LoadBalancer
   networkSecurityGroupId: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCEGROUPNAME}/providers/Microsoft.Network/networkSecurityGroups/${NSG}"
   managedIdentities:
     controlPlaneOperators:
       cloudControllerManager: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-cloud-controller-manager-${OPERATORS_UAMIS_SUFFIX}"
       cloudNetworkConfigManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-cloud-network-config-${OPERATORS_UAMIS_SUFFIX}"
       clusterApiAzureManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-cluster-api-azure-${OPERATORS_UAMIS_SUFFIX}"
       controlPlaneOperatorsManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-control-plane-${OPERATORS_UAMIS_SUFFIX}"
       diskCsiDriverManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-disk-csi-driver-${OPERATORS_UAMIS_SUFFIX}"
       fileCsiDriverManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-file-csi-driver-${OPERATORS_UAMIS_SUFFIX}"
       imageRegistryManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-image-registry-${OPERATORS_UAMIS_SUFFIX}"
       ingressManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-ingress-${OPERATORS_UAMIS_SUFFIX}"
       kmsManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-cp-kms-${OPERATORS_UAMIS_SUFFIX}"
     dataPlaneOperators:
       diskCsiDriverManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-dp-disk-csi-driver-${OPERATORS_UAMIS_SUFFIX}"
       fileCsiDriverManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-dp-file-csi-driver-${OPERATORS_UAMIS_SUFFIX}"
       imageRegistryManagedIdentities: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-dp-image-registry-${OPERATORS_UAMIS_SUFFIX}"
     serviceManagedIdentity: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUPNAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${USER}-${CS_CLUSTER_NAME}-service-managed-identity-${OPERATORS_UAMIS_SUFFIX}"
 visibility: Public
 network:
   machineCIDR: "10.0.0.0/16"
   podCIDR: "10.128.0.0/14"
   serviceCIDR: "172.30.0.0/16"
   hostPrefix: 23
   networkType: OVNKubernetes
 domainPrefix: ${CS_CLUSTER_NAME}
 version: "${OCP_VERSION}"
 channelGroup: stable
 versionGate: WaitForAcknowledge
 subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
 identityRef:
    kind: AzureClusterIdentity
    name: ${AZURE_CLUSTER_IDENTITY_NAME}
    namespace: ${AZURE_CLUSTER_IDENTITY_NAMESPACE}
 additionalTags:
   environment: production
   owner: sre-team
${EA_DISABLE} # External Authentication Configuration
${EA_DISABLE} # IMPORTANT: Replace the values below with your actual OIDC provider details
${EA_DISABLE} enableExternalAuthProviders: true
${EA_DISABLE} externalAuthProviders:
${EA_DISABLE}   - name: ${EA_OIDC_PROVIDER_NAME}
${EA_DISABLE}     issuer:
${EA_DISABLE}       # The URL of your OIDC provider (must use https://)
${EA_DISABLE}       issuerURL: "https://login.microsoftonline.com/${EA_AZURE_TENANT_ID}/v2.0"
${EA_DISABLE}       # Audience values that must be present in the JWT token
${EA_DISABLE}       audiences:
${EA_DISABLE}         - "${EA_AZURE_CLIENT_ID}"
${EA_DISABLE}       # Optional: Reference to a ConfigMap containing the CA certificate bundle
${EA_DISABLE}       # The ConfigMap should be in the same namespace and have a key "ca-bundle.crt"
${EA_DISABLE}       # issuerCertificateAuthority:
${EA_DISABLE}       #   name: oidc-ca-bundle
${EA_DISABLE}     # Optional: OIDC client configurations for OpenShift platform components
${EA_DISABLE}     # These are used by platform components to authenticate with the OIDC provider
${EA_DISABLE}     oidcClients:
${EA_DISABLE}       - componentName: "console"
${EA_DISABLE}         componentNamespace: "openshift-console"
${EA_DISABLE}         clientID: "${EA_AZURE_CLIENT_ID}"
${EA_DISABLE}         clientSecret:
${EA_DISABLE}           # Reference to a Secret containing the client secret in the "clientSecret" key
${EA_DISABLE}           name: "${EA_OIDC_CLIENT_SECRET_NAME}"
${EA_DISABLE}         extraScopes:
${EA_DISABLE}           - "openid"
${EA_DISABLE}           - "profile"
${EA_DISABLE}     # Optional: Define how JWT claims map to OpenShift user identities
${EA_DISABLE}     claimMappings:
${EA_DISABLE}       username:
${EA_DISABLE}         # The JWT claim to use for the username
${EA_DISABLE}         claim: "${EA_OIDC_USERNAME_CLAIM}"
${EA_DISABLE}         # How to handle username prefixing:
${EA_DISABLE}         # - "NoPrefix": Use claim value as-is
${EA_DISABLE}         # - "Prefix": Add a custom prefix (requires setting 'prefix' field)
${EA_DISABLE}         # - "" (empty): Default behavior (prefix with issuer URL for non-email claims)
${EA_DISABLE}         prefixPolicy: "NoPrefix"
${EA_DISABLE}         # Only required if prefixPolicy is "Prefix"
${EA_DISABLE}         # prefix: "myoidc:"
${EA_DISABLE}       groups:
${EA_DISABLE}         # The JWT claim containing group memberships (must be a string array)
${EA_DISABLE}         claim: "${EA_OIDC_GROUPS_CLAIM}"
${EA_DISABLE}     # Optional: Validation rules to enforce on JWT tokens
${EA_DISABLE}     # Tokens that don't match all rules will be rejected
${EA_DISABLE}     # Example: Require specific issuer
${EA_DISABLE}     # claimValidationRules:
${EA_DISABLE}     #   - type: "RequiredClaim"
${EA_DISABLE}     #     requiredClaim:
${EA_DISABLE}     #       claim: "iss"
${EA_DISABLE}     #       requiredValue: "https://your-oidc-provider.example.com"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AROMachinePool
metadata:
 name: ${CS_CLUSTER_NAME}-mp-0
 namespace: ${NAMESPACE}
spec:
  nodePoolName: ${NODEPOOL_PREFIX}-mp-0
  version: "${OCP_VERSION_MP}"
  platform:
    subnet: "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCEGROUPNAME}/providers/Microsoft.Network/virtualNetworks/${VNET}/subnets/${SUBNET}"
    vmSize: "Standard_D4s_v3"
    diskSizeGiB: 128
    diskStorageAccountType: "Premium_LRS"
  labels:
     region: ${REGION}
  # taints:
  #   - key: "example.com/special"
  #     value: "true"
  #     effect: "NoSchedule"
  additionalTags:
    environment: production
    cost-center: engineering
  autoRepair: true
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachinePool
metadata:
  name: ${CS_CLUSTER_NAME}-mp-0
  namespace: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/cluster-name: ${CS_CLUSTER_NAME}
spec:
  replicas: 2
  clusterName: ${CS_CLUSTER_NAME}
  template:
    spec:
      bootstrap:
        dataSecretName: ${CS_CLUSTER_NAME}-kubeconfig
      clusterName: ${CS_CLUSTER_NAME}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: AROMachinePool
        name: ${CS_CLUSTER_NAME}-mp-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AROCluster
metadata:
 name: ${CS_CLUSTER_NAME}
 namespace: ${NAMESPACE}
 labels:
   cluster.x-k8s.io/cluster-name: ${CS_CLUSTER_NAME}
spec:
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: ${CS_CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: AROControlPlane
    name: ${CS_CLUSTER_NAME}-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: AROCluster
    name: ${CS_CLUSTER_NAME}
---
