---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: ${AZURE_CLUSTER_IDENTITY_NAME}
  namespace: ${AZURE_CLUSTER_IDENTITY_NAMESPACE}
spec:
  allowedNamespaces: {}
  tenantID: "${AZURE_TENANT_ID}"
  clientID: "${AZURE_CLIENT_ID}"
  clientSecret:
    name: ${AZURE_CLUSTER_IDENTITY_SECRET_NAME}
    namespace: ${AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE}
  type: "ServicePrincipal"
---
apiVersion: v1
data:
  clientSecret: ${AZURE_CLUSTER_IDENTITY_SECRET_BASE64}
kind: Secret
metadata:
  name: ${AZURE_CLUSTER_IDENTITY_SECRET_NAME}
  namespace: ${AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
 name: aso-credential
 namespace: ${NAMESPACE}
stringData:
 AZURE_SUBSCRIPTION_ID: "${AZURE_SUBSCRIPTION_ID}"
 AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
 AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
 AZURE_CLIENT_SECRET: "${AZURE_CLIENT_SECRET}"
