# Resource: v1_service_capa-system_capa-metrics-service
---
{{- if .Values.global.deployOnOCP }}
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-metrics-service
  namespace: capa-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    cluster.x-k8s.io/provider: infrastructure-aws
  type: ClusterIP

{{- end }}