# Resource: v1_serviceaccount_capa-system_capa-controller-manager
---
{{- if .Values.global.deployOnOCP }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.amazonaws.com/role: '{{ .Values.aws.iamRole }}'
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    control-plane: controller-manager
  name: capa-controller-manager
  namespace: capa-system

{{- end }}