FROM golang:1.25-alpine
RUN apk add --no-cache \
    gcompat \
    libc6-compat \
    && \
    ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
RUN go install github.com/go-delve/delve/cmd/dlv@latest
COPY mce-capi-webhook-config /mce-capi-webhook-config
ENV HOME /tmp

