apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: ROSARoleConfig
metadata:
  name: "${ROLE_CONFIG}"
  namespace: "${NAMESPACE}"
spec:
  identityRef:
    kind: AWSClusterStaticIdentity
    name: "${CLUSTER_NAME}-account"
  accountRoleConfig:
    prefix: "${ROLE_PREFIX}"
    version: "${OPENSHIFT_VERSION}"
  operatorRoleConfig:
    prefix: "${ROLE_PREFIX}"
  credentialsSecretRef:
    name: "${ROSA_CREDS_SECRET}"
  oidcProviderType: Managed
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: ROSANetwork
metadata:
  name: "${ROSA_VPC}"
  namespace: "${NAMESPACE}"
spec:
  identityRef:
    kind: AWSClusterStaticIdentity
    name: "${CLUSTER_NAME}-account"
  region: "${AWS_REGION}"
  stackName: "${DOMAIN_PREFIX}-net"
  availabilityZones:
  - "${AWS_REGION}a"
  - "${AWS_REGION}b"
  - "${AWS_REGION}c"
  cidrBlock: 10.0.0.0/16
