# Resource: cert-manager.io_v1_certificate_capm3-system_capm3-serving-cert
---
{{- if not .Values.global.deployOnOCP }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-serving-cert
  namespace: capm3-system
spec:
  dnsNames:
  - capm3-webhook-service.capm3-system.svc
  - capm3-webhook-service.capm3-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capm3-selfsigned-issuer
  secretName: capm3-webhook-service-cert
{{- end }}