# Resource: v1_namespace_capm3-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
    pod-security.kubernetes.io/enforce: restricted
  name: capm3-system
