OCP_REGISTRY ?= registry.redhat.io

.PHONY: build-cluster-api-chart
build-cluster-api-chart:

.PHONY: build-cluster-api-aws-chart
build-cluster-api-aws-chart:

.PHONY: build-cluster-api-provider-azure-chart
build-cluster-api-azure-chart:

.PHONY: release-chart
release-chart: