apiVersion: apps/v1
kind: Deployment
metadata:
  name: capoa-controlplane-controller-manager
  namespace: capoa-controlplane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: capoa-controlplane-controller-manager
  template:
    metadata:
      labels:
        control-plane: capoa-controlplane-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: '{{ .Values.controlplane.image.url  }}:{{ .Values.controlplane.image.tag  }}'
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: capoa-controlplane-controller-manager
      terminationGracePeriodSeconds: 10
