# Resource: core_v1_namespace_capoa-controlplane-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capoa-controlplane-system
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: capoa-bootstrap-webhook-service
      namespace: capoa-bootstrap-system
      path: /validate-bootstrap-cluster-x-k8s-io-v1alpha1-openshiftassistedconfig
  failurePolicy: Fail
  name: validation.openshiftassistedconfig.bootstrap.cluster.x-k8s.io
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - openshiftassistedconfigs
  sideEffects: None