# Resource: core_v1_serviceaccount_capoa-controlplane-system_capoa-controlplane-controller-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capoa-controlplane-controller-manager
  namespace: capoa-controlplane-system