# Resource: rbac.authorization.k8s.io_v1_clusterrolebinding_capoa-controlplane-manager-rolebinding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capoa-controlplane-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capoa-controlplane-manager-role
subjects:
- kind: ServiceAccount
  name: capoa-controlplane-controller-manager
  namespace: capoa-controlplane-system
