---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_CLUSTER_API_AZURE}-hcpclusterapiproviderroleid-subnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}-${SUBNET}
    group: network.azure.com
    kind: VirtualNetworksSubnet
  principalIdFromConfig:
    name: identity-map-${MI_CLUSTER_API_AZURE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # 88366f10-ed47-4cc0-9fab-c8a06148393e represents 'hcpClusterApiProviderRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/88366f10-ed47-4cc0-9fab-c8a06148393e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-clusterapiazuremi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_CLUSTER_API_AZURE}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_KMS}-keyvaultcryptouserroleid-keyvault
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${KV}
    group: keyvault.azure.com
    kind: Vault
  principalIdFromConfig:
    name: identity-map-${MI_KMS}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # 12338af0-0e69-4776-bea7-57ae8d297424 represents 'keyVaultCryptoUserRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/12338af0-0e69-4776-bea7-57ae8d297424
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-kmsmi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_KMS}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_CONTROL_PLANE}-hcpcontrolplaneoperatorroleid-vnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}
    group: network.azure.com
    kind: VirtualNetwork
  principalIdFromConfig:
    name: identity-map-${MI_CONTROL_PLANE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # fc0c873f-45e9-4d0d-a7d1-585aab30c6ed represents 'hcpControlPlaneOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/fc0c873f-45e9-4d0d-a7d1-585aab30c6ed
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_CONTROL_PLANE}-hcpcontrolplaneoperatorroleid-nsg
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${NSG}
    group: network.azure.com
    kind: NetworkSecurityGroup
  principalIdFromConfig:
    name: identity-map-${MI_CONTROL_PLANE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # fc0c873f-45e9-4d0d-a7d1-585aab30c6ed represents 'hcpControlPlaneOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/fc0c873f-45e9-4d0d-a7d1-585aab30c6ed
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-controlplanemi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_CONTROL_PLANE}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_CLOUD_CONTROLLER_MANAGER}-cloudcontrollermanagerroleid-subnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}-${SUBNET}
    group: network.azure.com
    kind: VirtualNetworksSubnet
  principalIdFromConfig:
    name: identity-map-${MI_CLOUD_CONTROLLER_MANAGER}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # a1f96423-95ce-4224-ab27-4e3dc72facd4 represents 'cloudControllerManagerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/a1f96423-95ce-4224-ab27-4e3dc72facd4
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_CLOUD_CONTROLLER_MANAGER}-cloudcontrollermanagerroleid-nsg
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${NSG}
    group: network.azure.com
    kind: NetworkSecurityGroup
  principalIdFromConfig:
    name: identity-map-${MI_CLOUD_CONTROLLER_MANAGER}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # a1f96423-95ce-4224-ab27-4e3dc72facd4 represents 'cloudControllerManagerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/a1f96423-95ce-4224-ab27-4e3dc72facd4
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-cloudcontrollermanagermi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_CLOUD_CONTROLLER_MANAGER}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_INGRESS}-ingressoperatorroleid-subnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}-${SUBNET}
    group: network.azure.com
    kind: VirtualNetworksSubnet
  principalIdFromConfig:
    name: identity-map-${MI_INGRESS}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # 0336e1d3-7a87-462b-b6db-342b63f7802c represents 'ingressOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/0336e1d3-7a87-462b-b6db-342b63f7802c
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-ingressmi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_INGRESS}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-diskcsidrivermi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_DISK_CSI_DRIVER}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_FILE_CSI_DRIVER}-filestorageoperatorroleid-subnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}-${SUBNET}
    group: network.azure.com
    kind: VirtualNetworksSubnet
  principalIdFromConfig:
    name: identity-map-${MI_FILE_CSI_DRIVER}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # 0d7aedc0-15fd-4a67-a412-efad370c947e represents 'fileStorageOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/0d7aedc0-15fd-4a67-a412-efad370c947e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_FILE_CSI_DRIVER}-filestorageoperatorroleid-nsg
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${NSG}
    group: network.azure.com
    kind: NetworkSecurityGroup
  principalIdFromConfig:
    name: identity-map-${MI_FILE_CSI_DRIVER}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # 0d7aedc0-15fd-4a67-a412-efad370c947e represents 'fileStorageOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/0d7aedc0-15fd-4a67-a412-efad370c947e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-filecsidrivermi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_FILE_CSI_DRIVER}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-imageregistrymi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_IMAGE_REGISTRY}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_CLOUD_NETWORK_CONFIG}-networkoperatorroleid-subnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}-${SUBNET}
    group: network.azure.com
    kind: VirtualNetworksSubnet
  principalIdFromConfig:
    name: identity-map-${MI_CLOUD_NETWORK_CONFIG}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # be7a6435-15ae-4171-8f30-4a343eff9e8f represents 'networkOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/be7a6435-15ae-4171-8f30-4a343eff9e8f
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_CLOUD_NETWORK_CONFIG}-networkoperatorroleid-vnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}
    group: network.azure.com
    kind: VirtualNetwork
  principalIdFromConfig:
    name: identity-map-${MI_CLOUD_NETWORK_CONFIG}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # be7a6435-15ae-4171-8f30-4a343eff9e8f represents 'networkOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/be7a6435-15ae-4171-8f30-4a343eff9e8f
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-readerroleid-cloudnetworkconfigmi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_CLOUD_NETWORK_CONFIG}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # acdd72a7-3385-48ef-bd42-f606fba81ae7 represents 'readerRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-federatedcredentialsroleid-dpdiskcsidrivermi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_DP_DISK_CSI_DRIVER}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # ef318e2a-8334-4a05-9e4a-295a196c6a6e represents 'federatedCredentialsRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/ef318e2a-8334-4a05-9e4a-295a196c6a6e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-federatedcredentialsroleid-dpfilecsidrivermi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_DP_FILE_CSI_DRIVER}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # ef318e2a-8334-4a05-9e4a-295a196c6a6e represents 'federatedCredentialsRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/ef318e2a-8334-4a05-9e4a-295a196c6a6e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_DP_FILE_CSI_DRIVER}-filestorageoperatorroleid-subnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}-${SUBNET}
    group: network.azure.com
    kind: VirtualNetworksSubnet
  principalIdFromConfig:
    name: identity-map-${MI_DP_FILE_CSI_DRIVER}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # 0d7aedc0-15fd-4a67-a412-efad370c947e represents 'fileStorageOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/0d7aedc0-15fd-4a67-a412-efad370c947e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_DP_FILE_CSI_DRIVER}-filestorageoperatorroleid-nsg
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${NSG}
    group: network.azure.com
    kind: NetworkSecurityGroup
  principalIdFromConfig:
    name: identity-map-${MI_DP_FILE_CSI_DRIVER}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # 0d7aedc0-15fd-4a67-a412-efad370c947e represents 'fileStorageOperatorRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/0d7aedc0-15fd-4a67-a412-efad370c947e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-federatedcredentialsroleid-dpimageregistrymi
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${MI_DP_IMAGE_REGISTRY}
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # ef318e2a-8334-4a05-9e4a-295a196c6a6e represents 'federatedCredentialsRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/ef318e2a-8334-4a05-9e4a-295a196c6a6e
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-hcpservicemanagedidentityroleid-vnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}
    group: network.azure.com
    kind: VirtualNetwork
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # c0ff367d-66d8-445e-917c-583feb0ef0d4 represents 'hcpServiceManagedIdentityRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/c0ff367d-66d8-445e-917c-583feb0ef0d4
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-hcpservicemanagedidentityroleid-subnet
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${VNET}-${SUBNET}
    group: network.azure.com
    kind: VirtualNetworksSubnet
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # c0ff367d-66d8-445e-917c-583feb0ef0d4 represents 'hcpServiceManagedIdentityRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/c0ff367d-66d8-445e-917c-583feb0ef0d4
---
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: ${MI_SERVICE}-hcpservicemanagedidentityroleid-nsg
  namespace: ${NAMESPACE}
spec:
  owner:
    name: ${NSG}
    group: network.azure.com
    kind: NetworkSecurityGroup
  principalIdFromConfig:
    name: identity-map-${MI_SERVICE}
    key: principalId
  principalType: ServicePrincipal
  roleDefinitionReference:
    # c0ff367d-66d8-445e-917c-583feb0ef0d4 represents 'hcpServiceManagedIdentityRoleId'
    armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/c0ff367d-66d8-445e-917c-583feb0ef0d4

