manager:
  cmd: /manager
  image:
    tag: v5.0
    url: registry.stage.redhat.io/openshift5/ose-cluster-api-rhel9
webhook:
  image:
    tag: v5.0.0-1
    url: registry.stage.redhat.io/multicluster-engine/mce-capi-webhook-config-rhel9
