apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aro-mockup-proxy.fullname" . }}
  labels:
    {{- include "aro-mockup-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aro-mockup-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aro-mockup-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aro-mockup-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: https
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "aro-mockup-proxy.fullname" . }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: /data
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: tls
          mountPath: /tls
          readOnly: true
        {{- end }}
        {{- if .Values.kubeconfig.secretName }}
        - name: kubeconfig
          mountPath: /data/workload-kubeconfig.yaml
          subPath: {{ .Values.kubeconfig.key }}
          readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "aro-mockup-proxy.fullname" . }}
      {{- end }}
      {{- if .Values.tls.enabled }}
      - name: tls
        secret:
          secretName: {{ .Values.tls.secretName }}
      {{- end }}
      {{- if .Values.kubeconfig.secretName }}
      - name: kubeconfig
        secret:
          secretName: {{ .Values.kubeconfig.secretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
