name: CAPI tests (ARO)

on:
  pull_request:
    branches:
      - main
      - backplane-2.11
      - backplane-2.17
      - backplane-5.0
    paths:
      - "scripts/aro-hcp/**"
      - "charts/cluster-api-provider-azure-kind/**"
      - ".github/workflows/capi-tests.yaml"

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  capi-tests:
    uses: stolostron/capi-tests/.github/workflows/workload-cluster-aro.yml@main
    with:
      aro_repo_branch: ${{ github.head_ref }}
    secrets: inherit
