name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      dst-branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch to sync'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  call-sync:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/sync-providers.yaml
    with:
      dst-branch: ${{ inputs.dst-branch }}
    secrets:
      personal_access_token: ${{ secrets.GITHUB_TOKEN }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
