name: Sync providers

on:
  workflow_call:
    inputs:
      dst-branch:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true
      JIRA_API_TOKEN:
        required: true
env:
  JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
  JIRA_PROJECT: ${{ vars.JIRA_PROJECT }}
  JIRA_EPIC_LINK: ${{ vars.JIRA_EPIC_LINK }}

jobs:
  check-sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - short-name: capi
            project: cluster-api
            display-name: CAPI
            add-paths: "charts/cluster-api, src/cluster-api.yaml"
          - short-name: capa
            project: cluster-api-provider-aws
            display-name: CAPA
            add-paths: "charts/cluster-api-provider-aws, src/cluster-api-provider-aws.yaml"
          - short-name: capz
            project: cluster-api-provider-azure
            display-name: CAPZ
            add-paths: "charts/cluster-api-provider-azure"
          - short-name: capoa
            project: cluster-api-provider-openshift-assisted
            display-name: CAPOA
            add-paths: "charts/cluster-api-provider-openshift-assisted, src/cluster-api-provider-openshift-assisted.yaml"
          - short-name: metal3
            project: cluster-api-provider-metal3
            display-name: Metal3
            add-paths: "charts/cluster-api-provider-metal3, src/cluster-api-provider-metal3.yaml"
    steps:
    - name: show-env
      id: show-env
      run: |
        echo "env.JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}"
        echo "env.JIRA_PROJECT: ${{ env.JIRA_PROJECT }}"
        echo "env.JIRA_EPIC_LINK: ${{ env.JIRA_EPIC_LINK }}"
    - name: test-target-branch
      id: check-branch-exists
      uses: GuillaumeFalourd/branch-exists@v1.1 # the Apache License 2.0 - see https://github.com/marketplace/actions/branch-exists
      with:
        branch: ${{ format('{0}-pr-patches-{1}', inputs.dst-branch, matrix.short-name) }}
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.dst-branch }}
    - name: Sync
      id: sync
      run: make build-helm-charts
    - name: Create Pull Request
      id: cpr
      if: ${{ steps.sync.outputs[format('updated_{0}', matrix.project)] == 'true' && steps.check-branch-exists.outputs.exists == 'false' }}
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: ${{ matrix.display-name }} Update report
        add-paths: ${{ matrix.add-paths }}
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: ${{ format('{0}-pr-patches-{1}', inputs.dst-branch, matrix.short-name) }}
        delete-branch: true
        title: '[${{ matrix.display-name }}@${{inputs.dst-branch}}] Update report'
        body: |
          ${{ matrix.display-name }}@${{inputs.dst-branch}} Update report
          - Updated with *today's* date
        labels: |
          ${{ matrix.short-name }}
          report
          automated pr
        assignees: marek-veber
        reviewers: marek-veber
        draft: true
    - name: Create Jira task
      id: jira
      if: ${{ steps.sync.outputs[format('updated_{0}', matrix.project)] == 'true' && steps.check-branch-exists.outputs.exists == 'false' }}
      uses: fjogeleit/http-request-action@v1
      with:
        url: "${{ env.JIRA_BASE_URL }}/rest/api/2/issue/"
        bearerToken: ${{ secrets.JIRA_API_TOKEN }}
        data: |
            {
               "fields": {
                  "project":
                  {
                     "key": "${{ env.JIRA_PROJECT }}"
                  },
                  "summary": "[cluster-api-installer/${{ matrix.display-name }}@${{inputs.dst-branch}}] Please review the PR ${{ steps.cpr.outputs.pull-request-number }}",
                  "description": "[cluster-api-installer/${{ matrix.display-name }}@${{inputs.dst-branch}}] Update report - review request ${{ steps.cpr.outputs.pull-request-url }}",
                  "issuetype": {
                     "name": "Task"
                  }
              }
            }
        method: POST
    - name: Update epic in Jira task
      id: jira-epic
      if: ${{ steps.jira.outputs.status == '201' && fromJson(steps.jira.outputs.response).id != '' }}
      uses: fjogeleit/http-request-action@v1
      with:
        url: "${{ env.JIRA_BASE_URL }}/rest/api/2/issue/${{fromJson(steps.jira.outputs.response).id}}"
        bearerToken: ${{ secrets.JIRA_API_TOKEN }}
        data: |
            {
               "fields": {
                  "customfield_12311140": "${{ env.JIRA_EPIC_LINK }}"
              }
            }
        method: PUT
    - name: Show Jira task API Responses
      run: |
        echo "Response Status (create, update-epic): ${{ steps.jira.outputs.status }}, ${{ steps.jira-epic.outputs.status }}"
        echo "Response create Data: ${{ steps.jira.outputs.response }}"
        echo "Response update-epic Data: ${{ steps.jira-epic.outputs.response }}"
